"""models

Revision ID: 3b9b27f02f75
Revises:
Create Date: 2026-01-18 09:12:14.408293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b9b27f02f75"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_closed_at"), "departments", ["closed_at"], unique=False)
    op.create_index(op.f("ix_departments_department_id"), "departments", ["department_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_closed_at"), "projects", ["closed_at"], unique=False)
    op.create_index(op.f("ix_projects_project_id"), "projects", ["project_id"], unique=False)
    op.create_table(
        "skills",
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_closed_at"), "skills", ["closed_at"], unique=False)
    op.create_index(op.f("ix_skills_skill_id"), "skills", ["skill_id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.department_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_closed_at"), "employees", ["closed_at"], unique=False)
    op.create_index(op.f("ix_employees_employee_id"), "employees", ["employee_id"], unique=False)
    op.create_table(
        "employee_skill",
        sa.Column("employee_uuid", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_uuid"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("employee_uuid", "skill_id"),
    )
    op.create_table(
        "project_employee",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("employee_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_uuid"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "employee_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_employee")
    op.drop_table("employee_skill")
    op.drop_index(op.f("ix_employees_employee_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_closed_at"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_skills_skill_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_closed_at"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_projects_project_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_closed_at"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_departments_department_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_closed_at"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
